### ISSUE TITLE
Homebridge plugin?

### ISSUE THREAD

**Issue by ryanmaxwell** [lennyby93/node-mmcontrol#1]
Hey, thanks for this project, i'm going to give a try tonight with my heat pumps. 
Are you an iOS user? I'm thinking about creating/adapting this project for use as a [Homebridge](https://github.com/nfarina/homebridge) plugin. There are some other Heat pump homebridge plugins such as [Sensibo](https://github.com/pdlove/homebridge-sensibo) which may be useful as a reference implementation. What do you think?

**Comment by lennyby93** [comment]
I didn't look too deep into it but I don't think it should be too difficult to implement a plugin for Homebridge. That Sensibo plugin looks straightforward enough, but I have no iOS device I could test that with.

**Comment by ryanmaxwell** [comment]
@lennyby93 thanks for that, my JS skills are a bit rusty but i'll give it a try when I have time!

**Comment by NovaGL** [comment]
Any update on this?

**Comment by jclendon** [comment]
I'm interested in a Homebridge plugin using mmcontrol too. If no one else has started it I might give it a crack. On and off are all I'll probably start with.
