### ISSUE TITLE
Practical home automation use of node-mmcontrol

### ISSUE THREAD

**Issue by afalout** [lennyby93/node-mmcontrol#4]
Hi Lenny,

thank you very much for sharing this library with us!

My question/suggestion is:

How does someone without coding experience use this, to automate functions and integrate the heat pump into home automation workflows?

I am thinking about user-level setup. maybe IFTTT (https://ifttt.com/maker_webhooks) or Alexa that you mentioned in the discussion on https://forums.whirlpool.net.au/archive/2339081

Any suggestions very much appreciated!

**Comment by NovaGL** [comment]
There are several complexities for this for the average user.

First complexity is authentication How are you going to tell IFTTT who you are and have a facility to store that information. 

Second is how are you going to know the rooms and which one you want to select. The next one is passing the authentication with the command that you want knowing the device supports those functions.

The best way I see you doing this is having some middleware that controls the actions.

I use Node-Red which stores the information and translates it into the relevant command.

The means if you type bedroom it knows its unit 123 or if you say temp 99 it will let you know it's invalid.

Alexa is very static when it comes to home skills. 

I don't know how to dynamically create the aircon units in Alexa so I create them one by one.

If you are curious to see how the command is actually processed view my repo here
https://github.com/NovaGL/diy-melview

**Comment by afalout** [comment]
Thanks for your reply!

I also use Node-red, is there a Node-red node/flow package somewhere that I missed ? Here in git I see only general node.js module that cannot be used with Node-red without a re-write/wrapper ...?

Thanks

**Comment by NovaGL** [comment]
No. It is very possible but beyond my skill level.

I have done mine in Node-red but its tailored to Alexa.

Maybe I'll post the flow when it works without Alexa but my repo (really just a gist) should give you a good understanding for you to do it yourself

**Comment by afalout** [comment]
I have Amazon Echo so I would be very interested to see your flow with Alexa... any chance you would consider sharing it?

I am having a difficulty picturing what exactly to do with node.js code in Node-RED... probably just dont understand Node-RED well enough, but cannot figure out a way to use your code in it. Seeing a workflow of any kind would help a lot...

Thanks,
Andrej

**Comment by NovaGL** [comment]
I don't use this code at all. I do it all through the http node.

I will consider it but as you know with code its easy to get tangled up with other things
